sudo: required

services:
  - docker

before_script:
  # - curl https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/before-test.sh -o /tmp/before-test.sh
  # - source /tmp/before-test.sh
  - source bin/before-test.sh

script:
  - $QA_PATH/bin/test.sh


# language: ruby
#
# env:
#   - TRAVIS_NODE_VERSION="6"
#
# cache:
#   - ~/.travis-bundler-gems
#   - ~/frontend/node_modules
#   - $TRAVIS_BUILD_DIR/node_modules

# before_script:
#   - curl https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/before-test.sh -o /tmp/before-test.sh
#   - source /tmp/before-test.sh
#
# script:
#   - curl -s https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/test.sh -o /tmp/test.sh
#   - bash /tmp/test.sh
