language: ruby
cache: bundler

# TODO: Fill in the correct BEFORE_SCRIPT_URL
before_script:
  - bash <(curl -s BEFORE_SCRIPT_URL)

# TODO: Fill in the correct TEST_SCRIPT_URL
script:
  - bash <(curl -s TEST_SCRIPT_URL)

# TODO: Fill in notification preferences
notifications:
  email:
    - insert_email
  slack: smashingboxes:some_number # TODO
