language: ruby
cache: bundler

before_script:
  - bash <(curl -s https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/before-test.sh)

script:
  - bash <(curl -s https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/test.sh)
